<?php

########################################################################
# Extension Manager/Repository config file for ext: "simply_slideshow"
#
# Auto generated by Extension Builder 2012-06-06
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Slideshow',
	'description' => 'A simple slide show based on the jQuery cycle plugin',
	'category' => 'plugin',
	'author' => 'Henjo Hoeksma',
	'author_email' => 'hphoeksma@stylence.nl',
	'author_company' => 'Stylence',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'extbase' => '1.3.0',
			'fluid' => '1.3.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>